name: deploy

on:
  push:
    branches:
      - main

jobs:
  update-cv:
    name: update-cv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install weasyprint
        run: sudo apt install weasyprint

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install project dependencies
        run: uv sync

      - name: Generate static assets
        run: uv run python -m cv.generate

      - name: Debug action
        run: |
          pwd
          ls

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build SWS image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/damienallen/cv:latest
          cache-from: type=registry,ref=ghcr.io/damienallen/cv:latest
          cache-to: type=inline
